### ISSUE TITLE
NTP循环校正时间

### ISSUE THREAD

**Issue by 630281661** [Yh793/Padavan-build#1]

**Comment by 630281661** [comment]
在C大源码升级busybox到1.31.1时，遇到日志每隔30秒到5分钟，提示ntp校时，一直循环。不知道你的遇见过这种问题没

**Comment by 630281661** [comment]
![Screenshot_2020-11-15-18-14-11-197_jp sblo pandora jota plus](https://user-images.githubusercontent.com/65788659/99182207-879c8600-276e-11eb-8dc6-647bd7aba3e8.png)

**Comment by 630281661** [comment]
![Screenshot_2020-11-15-18-14-11-197_jp sblo pandora jota plus](https://user-images.githubusercontent.com/65788659/99182222-9daa4680-276e-11eb-8cb6-d263040fde23.png)
目前临时解决办法如图

**Comment by Yh793** [comment]
git clone -b busybox --depth=1 https://github.com/Yh793/rt-n56u.git /opt/rt-n56u
你用这个分支编译测试看有没有问题。
