### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by luoluodaduan** [Yh793/Padavan-build#2]
大佬源码修改很好用 trunk/user/miniupnpd/miniupnpd-2.x/miniupnpd.c 下的 sleep(40); 修改为啥删除了 是不是有问题?

**Comment by Yh793** [comment]
没什么问题，这是我复制来的。你用miniupnpd的话可以自己加上。

**Comment by Yh793** [comment]
https://github.com/hanwckf/rt-n56u/pull/383

**Comment by luoluodaduan** [comment]
谢了大佬
